import { useState } from "react";
import { generateArticle } from "../../aiService";
import "./Articles.css";

const topics = [
  { label:"Market Trends 2026", class:"article-trends" },
  { label:"Crypto & Blockchain in India", class:"article-crypto" },
  { label:"Top Performing Stocks Q1 2026", class:"article-stocks" },
  { label:"Managing Risk in Volatile Markets", class:"article-risk" },
  { label:"Mutual Funds Outlook 2026", class:"article-funds" },
];

export default function Articles() {
  const [articles, setArticles] = useState({});
  const [loading, setLoading] = useState({});

  const generate = (topic) => {
    setLoading(l => ({...l,[topic]:true}));
    generateArticle(topic).then(text => setArticles(a => ({...a,[topic]:text}))).catch(console.error).finally(() => setLoading(l => ({...l,[topic]:false})));
  };

  return (
    <div className="articles-container">
      <h2 className="articles-heading">📰 Nextgen AI — Articles</h2>
      <p className="articles-text">Click any topic to generate a live AI-written article for Indian investors.</p>
      <div className="articles-grid">
        {topics.map(t => (
          <div key={t.label} className={`article-card ${t.class}`}>
            <h3>{t.label}</h3>
            <button onClick={() => generate(t.label)}
              style={{marginTop:"8px",background:"#1e40af",color:"#fff",border:"none",borderRadius:"6px",padding:"6px 12px",fontSize:"11px",cursor:"pointer",fontFamily:"Segoe UI,sans-serif"}}>
              {loading[t.label] ? "🤖 Writing..." : "✍️ Generate AI Article"}
            </button>
            {articles[t.label] && <p style={{fontSize:"12px",marginTop:"10px",lineHeight:"1.6",color:"#1e293b"}}>{articles[t.label]}</p>}
          </div>
        ))}
      </div>
      <div className="articles-summary"><h3>🤖 Editor's Note</h3><p>All articles are AI-generated by Nextgen ShareMarket & AI for informational purposes. Always verify with SEBI-registered advisors.</p></div>
    </div>
  );
}
